language: r
sudo: false
cache: packages

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libcurl4-openssl-dev

r_github_packages:
  - jimhester/covr

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - Rscript -e 'covr::codecov()'
